# Generated by Django 4.2.5 on 2023-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='DName',
            field=models.CharField(choices=[('1', 'Dr Arnav Osborne'), ('2', 'Dr Muskan Singh'), ('3', 'Dr Morgan Hester'), ('4', 'Dr Suraj Sandal'), ('5', 'Dr Sanjit Nayar'), ('6', 'Dr Aahana Kaur')], default='1', max_length=1),
        ),
    ]
